# API Keys - DO NOT COMMIT TO GIT!
# Add this file to your .gitignore

fred:
  api_key: "YOUR_FRED_API_KEY_HERE"

newsapi:
  api_key: "YOUR_NEWS_API_KEY_HERE"  # For future news sentiment

# Environment-specific keys
development:
  fred_api_key: "dev_key_here"

production:
  fred_api_key: "prod_key_here"
